name: Deploy Vertex AI GPU Container

on:
  push:
    branches: [ main ]
    paths:
      - 'gpu_worker.py'
      - 'Dockerfile.gpu'
      - 'requirements-gpu.txt'
      - 'caption_generator.py'
      - 'vertex_gpu_service.py'
  workflow_dispatch:

env:
  PROJECT_ID: av-8675309
  IMAGE_NAME: av-gpu-job
  REGION: us-central1
  WORKLOAD_IDENTITY_PROVIDER: projects/939407899550/locations/global/workloadIdentityPools/github-pool/providers/github-provider
  SERVICE_ACCOUNT: github-actions@av-8675309.iam.gserviceaccount.com

jobs:
  deploy-vertex-gpu:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and Push Vertex AI GPU Container
      run: |
        echo "🚀 Building GPU container for Vertex AI..."
        echo "Project ID: $PROJECT_ID"
        echo "Image: gcr.io/$PROJECT_ID/$IMAGE_NAME"
        
        docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }} -f Dockerfile.gpu .
        docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:latest -f Dockerfile.gpu .
        
        echo "📤 Pushing container..."
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }}
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

    - name: Create GCS bucket for jobs
      run: |
        BUCKET_NAME="$PROJECT_ID-video-jobs"
        echo "📦 Creating GCS bucket: $BUCKET_NAME"
        gsutil mb -p $PROJECT_ID -c STANDARD -l $REGION gs://$BUCKET_NAME/ 2>/dev/null || echo "Bucket already exists"

    - name: Test GPU container deployment
      run: |
        echo "✅ Vertex AI GPU container deployed successfully!"
        echo "Image: gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }}"
        echo "Latest: gcr.io/$PROJECT_ID/$IMAGE_NAME:latest"
        echo ""
        echo "The main application will automatically use this container for video processing." 